Insert Into producenci (id_producenta, producent) Values (1, 'H&M');
Insert Into producenci (id_producenta, producent) Values (2, 'Nike');
Insert Into producenci (id_producenta, producent) Values (3, 'Adidas');
Insert Into producenci (id_producenta, producent) Values (4, 'Gap');
Insert Into producenci (id_producenta, producent) Values (5, 'Lululemon Athletica');
Insert Into producenci (id_producenta, producent) Values (6, 'ZARA');
Insert Into producenci (id_producenta, producent) Values (7, 'Puma SE');
Insert Into producenci (id_producenta, producent) Values (8, 'Under Armour');
Insert Into producenci (id_producenta, producent) Values (9, 'Fast Retailing');
Insert Into producenci (id_producenta, producent) Values (10, 'Inditex');
